### ISSUE TITLE
Clean-up: Unused images/workflows

### ISSUE THREAD

**Issue by rohank07** [StatCan/aaw-contrib-containers#105]
After our clean up of the ACR, a lot of the images are no longer used. Plus workflows for serveral images are failing. Some of them being: `/constrstarts-geo` `/btap` `/constrstarts-fastai`

**Comment by vexingly** [comment]
@rohank07 do we have an 'owner' for all of the images? We should ensure that someone is identified (and documented) as a contact for all of the repos, it will make cleanup easier in the future :)

**Comment by rohank07** [comment]
I agree. Other than going by the name of the image, its hard to tell who the owner is for some of the images. Going forward we should have a readme for each DockerFile.

**Comment by Jose-Matsuda** [comment]
Placeholder comment (to be edited with details)
